### ISSUE TITLE
multiple workers

### ISSUE THREAD

**Issue by FredericaBernkastel** [mserajnik/hydrusrv#10]
Since node is single-threaded, if one user will perform a long file query, e.g. 1 second, api will be  unaccessible for everyone else during 1 second.
Check this: https://nodejs.org/api/cluster.html

Ofcourse, it's possible to run multiple instances, but this is just stupid, and giant waste of resources.

**Comment by mserajnik** [comment]
The main issue here is the synchronous API of better-sqlite3 than anything else. If the calls could be usynchronous, then having only a single thread wouldn't make the API unavailable while a query runs (the application would probably still need a few adjustments, but probably not a huge effort).

Unfortunately, there [aren't any plans to provide an usynchronous API](https://github.com/JoshuaWise/better-sqlite3/issues/89). Still, don't really want to switch better-sqlite3 out though, since it's a lot faster than all the other SQLite wrappers for Node.

Running a cluster would be a possible solution, though there are some things that would need to be changed.

E.g., the worker that updates the data is currently attached to the Express app, so duplicating the app would also duplicate that worker (and therefore probably cause at least memory issues, because every worker would have its own set of data).

But since the created tables are temporary, they aren't accessible outside of the connection that created it, so we can't _just_ detach that worker from the Express apps running in the cluster (because then we'd still need to access the same DB connection from the apps, so we gain nothing).

Simply not having the tables temporary would work, but then it would write to disk every time we update (SQLite keeps temporary tables only in memory, if possible), which would be _bad_ with large databases (writing several GB of data every 30 minutes or whatever update time is set probably isn't healthy for the disk if that runs 24/7 for months or years).

So… not 100% sure what the best way to solve this would be. I'll look into it when I find the time. 👍

**Comment by mserajnik** [comment]
> Isn't there mechanisms in node to make shared memory between child processes?

[Doesn't look like it](https://github.com/nodejs/help/issues/560).

**Comment by mserajnik** [comment]
> If there are timestamps for each new mapping, coupled with information about deleted files and mappings from corresponding tables, will it be possible to write only differences since last update?

You mean so we could write the DB to disk without worries about too much degradation?

Imo, no, since there's so much data that can change aside from mappings. I think it would be a lot slower needing to compare everything than just discarding all the data and fetching everything again, as we do now.

Recognizing newly added mappings for example is easy (as you said, we have a timestamp for those), but what about deleted ones? Sure, there's a `deleted_mappings_x` table, but that won't be persisted forever by hydrus, so we can't rely on that (especially if the user sets the update time really long, e.g., a week). How fast would it be to compare 20m mappings and see if they still exist in the hydrus database? Same for files and tags.

Also, using persistent tables will be a lot slower than temporary ones because SQLite will not have everything in memory at all times (would be impossible here anyway, imagine 16 threads, each with a fully copy of a DB with several in memory).

> Using separate database engine?

A few things that speak against this:

1. You've just made the updates a LOT faster by selecting and inserting the data at the same time. We'd lose that if we were to use a different DB, because hydrus will always use SQLite, no matter what we do.
2. I don't think any other SQL implementation is much faster than SQLite when it comes to reading. Afaik, most are usually slower when reading, so performance for the end user would degrade (at least a bit).
3. Using a NoSQL implementation like MongoDB instead would work to make everything asynchronous, but would require a very different approach when it comes to the relations we need to model.

So, not sure about this. Could be a solution? But going a completely different route (e.g., MongoDB) would also mean a rewrite of large parts of hydrusrv (aside from being a breaking change). Instead of investing that time, you could easily just rewrite the whole application in a different language with a fast SQLite wrapper that supports asynchronous requests. The frontend fortunately doesn't care, as long as the API stays the same.

**Comment by mserajnik** [comment]
The workers spawn just fine, but I can't seem to share the DB connection between workers.

Normally, requiring a file that exports an object will always return the same object in Node.js, which is handy for keeping DB connections alive without needing to pass the handle around through the whole application.

However, the same object doesn't seem to be shared between workers, so if I open a DB connection in the master and then try to use that handle in a worker, it doesn't work because the handle simply doesn't exist (because each worker gets a new instance of the object).

Now, the creator of better-sqlite3 writes:

> using IPC to pass around socket handles

But to be frank, no idea how that would work. It does seem to work to pass the object with the handle in a message to the workers, but even then it only seems to keep plain objects (and not the attached functions).

And even if that did work, it would require to pass the DB object around in the whole application, which seems like _really bad_ practice.

There might be a different way that I don't know about, of course.

---

On a different note, [in-memory](https://www.sqlite.org/inmemorydb.html) databases sound interesting. Unlike temporary tables/databases, they can be shared between connections. And since we don't associate any user data with files/tags anyway, there's no reason for us to use the same (persistent) database that's used for users anyway.

The big __but__ here is, that they only seem to be shared between connections in the same process, so that probably won't work either. :/

---

__To sum up:__

I don't think there's an easy way to solve this. We either

1. sacrifice speed and risk degrading hardware really fast by writing the temporary data to the disk
2. try to come up with an efficient way to only update data that's changed so we won't need to rewrite everything each update
3. use a different SQLite wrapper that allows for asynchronous connections, potentially making single queries much slower but allowing multiple users to query at the same time because we can do it asynchronously
4. use a different DB, likely sacrificing update speed (because we can't do selects and inserts in the same query anymore) and requiring potentially a big rewrite and a vastly different approach for performance optimization (especially if we switch to a completely different technology like MongoDB)

1.) is probably off the table, 2.) sounds reasonable, but hard to implement without making it slow with big databases (at least to me), 3.) potentially makes performance worse for single users, which this was mainly intended for, so not a fan, 4.) sounds reasonable, but we'd probably still need to deal with 1.) and 2.) when switching if the technology used doesn't provide in-memory storage.

Gonna flag this with `help wanted` because I don't see myself having the time to tackle any of these approaches anytime soon, sorry.

But to be clear: I'm not inherently opposed to any idea, even if it would be a breaking change or make the setup a bit more difficult.

**Comment by mserajnik** [comment]
I just had an idea about how to implement 2.) without too much effort and while (hopefully) keeping the updates efficient. I'll give it a try and report back.

**Comment by mserajnik** [comment]
Here: https://github.com/mserajnik/hydrusrv/tree/feature/persist-hydrus-data

Could you give that a try? You'll need to run `yarn migrate` for the new tables.
__Please don't try it in a production environment.__ :D

Basically:

+ We still create temporary data tables
+ Those temporary tables are then compared to persistent ones -> deleted data is removed first before new data is added

I only compare the IDs but having another look at the hydrus server database handling, I think they shouldn't get overriden. Takes around 200ms initially for my set of `[ namespaces: 6, files: 1992, tags: 2449, mappings: 38823 ]`, and if there weren't any changes at the next update, it takes about 5ms. Not sure if those queries can be made even more efficient?

Query performance also seems to be ok, don't really see any difference – but there probably will be at least a small one with larger databases than reading straight from memory, I think.

I think this should work – or did I miss something?

__Note:__ I threw this together rather quickly, so I didn't split it up into multiple functions or anything yet. It's just a proof of concept.

With this, we could implement the cluster where every worker has its own DB connection.

**Comment by FredericaBernkastel** [comment]
3. Actually i thought about sqlite backend, written on different language. We'd still save update speed in this case.
4. In linux, there is a thing called [tmpfs](https://en.wikipedia.org/wiki/Tmpfs), we can just place entire db there.

**Comment by mserajnik** [comment]
3. How would this help us with the fact that we _need_ to persist the data so we can have multiple connections when running Node.js workers?
4. Not really, since hydrusrv also needs to run on Windows and macOS

**Comment by FredericaBernkastel** [comment]
sqlite backend will store all data in memory, listen for requests from multiple workers, and asynchronously read the data from db.

**Comment by mserajnik** [comment]
Not a fan, sorry. I don't want to add yet another layer. You are of course free to implement it and (re-)use anything from here, but I wouldn't want that in this application.

On a side note, I've amended the commit once more. Mappings and namespaces should now update correctly as well. I think this works well. Add the workers to it and I think this is a decent solution.

**Comment by mserajnik** [comment]
Hmm, looks like it's missing one namespace for some reason.

Regardless, I just did some testing with Robert's DB. I needed to make some adjustments because apparently hydrus _can_ reuse old IDs. So I had to join on two columns (e.g., `id` and `hash` for files and `id` and `name` for tags).

First persist took about 10 seconds which was pretty good, but then it went downhill. Next update took 47 seconds when no data was changed (due to all the necessary comparisons). I then changed the name of all the persisted tags to trigger mismatches for every single tag – I cancelled it after 180 seconds.

I can't think of a better way to check if any data has changed, so… this is probably not viable, unfortunately. :(

---

Sorry, I think i misread your idea before. For some reason, I read hydrusrvue instead of hydrusrv and thought you wanted to add _an additional_ server that holds the hydrus data and serves that directly to the frontend. But you want it to sit between hydrusrv and the database, correct? So nothing would change for the client.

I'm not opposed to that. Do you have any concrete ideas?

**Comment by FredericaBernkastel** [comment]
From 20k/695k deleted 1.2k/57k. Update stuck for 270 seconds. Yeah.

> concrete ideas

C# should be quite easy solution: [[sqlite multithread]](https://stackoverflow.com/questions/15383615/multiple-access-to-a-single-sqlite-database-file-via-system-data-sqlite-and-c-sh), [[async TCPListener example]](https://gist.github.com/Maxwe11/cf8cc6331ad73671846e).
db connection can be made [in-memory](https://www.sqlite.org/inmemorydb.html) as you told before.

It will just sit on local port, receive requests from hydrusrv, and do all the job.
From hydrusrv, you will need just to make a get request to it.

**Comment by mserajnik** [comment]
Sounds good, so all the hydrus data handling would be moved to this C# app – hydrusrv will still keep its SQLite DB as it‘s used for the user handling.

Not sure if the C# app should be in a separate repository or not, but for the sake of convenience (also when using Docker), I‘d probably rather keep it in here (and just make a new major release, then it‘s no issue if the user needs to do additional steps to build it). It could then also easily use the same config file.

Any objections?

The only thing is, I have no prior experience with C#, so unless you want to do it, it might be a while before I get around. Although, I would like the challenge. :)

**Comment by FredericaBernkastel** [comment]
I'll write proof of concept.

**Comment by mserajnik** [comment]
But I‘m not sure if we should keep hydrusrv at all the way it is in this case – wouldn‘t it be easier to handle everythin in the new app and make that basicslly a rewrite of hydrusrv?

Granted, rewriting everything in C# is a bit daunting. Personally, I‘d rather do it in Go, maybe based on [Iris](https://github.com/kataras/iris), in such a case.

Or do you think it will actually be benefitial to the performance to offload the data handling but still have hydrusrv as the „middle man“ that handles users and authentication?

**Comment by FredericaBernkastel** [comment]
Not a fan of making zoo of technologies.
But current auth realization bothers me, because all users are forced to register, and most of them just leave my site due this.

**Comment by mserajnik** [comment]
Agreed, that‘s why I‘m not sure if it wouldn‘t be better to have a single service written in a language where we can easily get the desired functionalty working wouldn‘t be better than adding a new service in a different language to an already established one.

Regarding the authorization: I hear you, it‘s already on my list of things to do.

The media token is there so

**Comment by mserajnik** [comment]
Sorry, misclicked, didn‘t mean to close this. :D

**Comment by mserajnik** [comment]
Some more thoughts after sleeping on it:

+ I think regardless of the DB used, writing everything to disk with every update is the only sane approach if we don't want headaches. Probably won't be more than 100MB for the average user, not the "several GB of data" I've talked about before. Even Robert's rather large DB only takes about 150MB on disk. Doing this every hour or so at the most should be fine, a disk can easily handle that without degrading any faster than a disk used for every-day tasks. And you could even argue that updating every hour is overkill, unless you have multiple users inserting data into hydrusrv all the time. Plus, we could easily hash the tables and then compare those hashes on update – if not a single hash has changed, nothing has changed in the DB and we won't have to rewrite to disk. That's a fast and easy comparison. Finally, on many Unix systems, the user can just put the data on a tmpfs manually (we will just use separate DBs for user data and hydrus data, so user data doesn't have to be on tmpfs and won't be lost on shutdown).
+ Aside from that, I really think getting rid of the synchronous calls is the top priority, so I'd either give a different SQLite wrapper a try or use a different DB altogether. __But__, in the end, SQLite is serialized by nature, so even asynchronous calls will only get us so far. Using PostgreSQL ([node-postgres](https://github.com/brianc/node-postgres) is pretty awesome from what I've heard) or anything else that allows for concurrent reads _might_ be preferable.
+ Express/the HTTP functionality in Node.js in general is plenty fast on a single process _if_ nothing is blocking it. If we don't hold all the data in memory for every process, there's no need to force multiple processes using a Node.js cluster inside the application. Scaling it up further could instead always be done by the user via [PM2](http://pm2.keymetrics.io/) (on an application-level, this actually uses Node.js clusters internally) or Kubernetes (on a container-level) for example, which many will prefer anyway because they can finetune it for the use case and hardware they run on.
    + I actually don't expect this to be needed if it would be only a few hundred requests per second, so I would just make sure that it works, but leave the rest of this setup entirely to the user if he wants/needs to do it

Imo, we've been overcomplicating this.

Yes, having a dedicated service that handles all the data might make sense if we wanted to scale this to an insane amount of concurrent requests. But, as said above, you can always scale up in other (arguably better) ways, if needed. And if we persist the data (which I _really_ think we should), there's nothing gained anyway, we can do everything right from Node.js and don't have the overhead of having to run a separate application that communicates via TCP.

---

I will do some testing of these concepts on the weekend and report back.

If you have RAM to spare on your production machine (since the hydrus data will be duplicated for every process, but even Robert's DB only took about 50MB in memory, so shouldn't be too bad I hope), I guess you could already use the mentioned [PM2](http://pm2.keymetrics.io/) to improve performance for multiple users at the same time as a temporary workaround. I haven't tested it, but I don't think there's anything that would prevent it from working right now.

**Comment by mserajnik** [comment]
Next steps for me:

1. Complete a larger refactoring I've started today (there's quite a bit that needs cleaning up and I want to do this first before tackling any bigger tasks)
2. Implement the ability to make registration optional in both the server and the client (so it can act as a public installation)
3. Explore some solutions to this issue, mainly the ones mentioned in my last comment (so, probably: move the data update task to its own process/application so it won't block the API while it's running (it's actually the biggest offender, especially on large DBs), try switching to PostgreSQL and persisting data, check how performance compares)

You are of course free to explore other solutions (e.g., your proposed C# service that communicates via TCP) if you want. That's also why I'll do 2.) before 3.), so that is out of the way.

**Comment by FredericaBernkastel** [comment]
Nice trick with copy, haha.
I've just solved the headache with sqlite in C#, and missing regexp function.
Performance is the same as better-sqlite3... promising.
I'll show detailed info in few days.

**Comment by mserajnik** [comment]
I've run into memory issues on large tables (10m+ mappings) where the application crashes after memory goes up to about 1.5GB used due to the heap being exceeded when fetching the data from SQLite. The transformation to CSV and insert into PostgreSQL itself doesn't take much, it's really just all that data that's shoved into memory, so even saving to a file first doesn't help.

I've tried chunking up the query, but using `LIMIT`/`OFFSET` is painfully slow (~50 times slower than fetching everything at once, reading and inserting 10m mappings took about half an hour), even if using reasonably large chunks of 100k rows.

"Conveniently", the hydrus server mappings table doesn't have an incrementing ID and is also created `WITHOUT ROWID`, so I can't do something like `SELECT * FROM mappings WHERE rowid IN (<actual query that limits the mappings and returns the rowids>)`, which would probably be a lot faster.

Tbh, at this point I'm getting frustrated. This approach looked so promising and I've already invested a decent amount of time, only to be "shot down" by a stupid issue like this.

I'll take a few weeks off from this project. I really need to get my head clear and have some other stuff that can use the attention better atm anyway.

Therefore, sorry, but I'll have to postpone the planned release this weekend to a yet uncertain date in the future and I likely won't reply to any comments in the meantime.

**Comment by FredericaBernkastel** [comment]
Sure. 
Just update hydrusrvue aswell to reflect optional registration, before going out.

**Comment by mserajnik** [comment]
[Done](https://github.com/mserajnik/hydrusrvue/tree/1.12.0). Was actually far easier than I thought because apparently, I had unconsciously already accounted for almost everything that was needed.

**Comment by mserajnik** [comment]
I have yet to do any comparisons, but this is a local test using [loadtest](https://github.com/alexfernandez/loadtest) sending 300 requests per second from 300 clients (so 1 request per client per second) when running 8 workers:

```
➜ loadtest -c 300 --rps 300 'http://localhost:8000/api/files?page=1&tags[]=tree&tags[]=house&tags[]=-sky&sort=namespaces&namespaces[]=creator&namespaces[]=series'
[Fri Nov 30 2018 17:39:32 GMT+0100 (Central European Standard Time)] INFO Requests: 0, requests per second: 0, mean latency: 0 ms
[Fri Nov 30 2018 17:39:37 GMT+0100 (Central European Standard Time)] INFO Requests: 1499, requests per second: 300, mean latency: 16.3 ms
[Fri Nov 30 2018 17:39:42 GMT+0100 (Central European Standard Time)] INFO Requests: 2997, requests per second: 300, mean latency: 14.6 ms
[Fri Nov 30 2018 17:39:47 GMT+0100 (Central European Standard Time)] INFO Requests: 4493, requests per second: 298, mean latency: 16.6 ms
[Fri Nov 30 2018 17:39:52 GMT+0100 (Central European Standard Time)] INFO Requests: 5990, requests per second: 300, mean latency: 32.5 ms
[Fri Nov 30 2018 17:39:57 GMT+0100 (Central European Standard Time)] INFO Requests: 7499, requests per second: 302, mean latency: 22.6 ms
[Fri Nov 30 2018 17:40:02 GMT+0100 (Central European Standard Time)] INFO Requests: 8999, requests per second: 300, mean latency: 15.3 ms
[Fri Nov 30 2018 17:40:07 GMT+0100 (Central European Standard Time)] INFO Requests: 10498, requests per second: 300, mean latency: 14.8 ms
[Fri Nov 30 2018 17:40:12 GMT+0100 (Central European Standard Time)] INFO Requests: 11996, requests per second: 300, mean latency: 17.5 ms
[Fri Nov 30 2018 17:40:17 GMT+0100 (Central European Standard Time)] INFO Requests: 13498, requests per second: 300, mean latency: 18.7 ms
[Fri Nov 30 2018 17:40:22 GMT+0100 (Central European Standard Time)] INFO Requests: 14997, requests per second: 300, mean latency: 19 ms
[Fri Nov 30 2018 17:40:27 GMT+0100 (Central European Standard Time)] INFO Requests: 16497, requests per second: 300, mean latency: 24.7 ms
[Fri Nov 30 2018 17:40:32 GMT+0100 (Central European Standard Time)] INFO Requests: 17997, requests per second: 300, mean latency: 17.3 ms
[Fri Nov 30 2018 17:40:37 GMT+0100 (Central European Standard Time)] INFO Requests: 19499, requests per second: 300, mean latency: 22.2 ms
[Fri Nov 30 2018 17:40:42 GMT+0100 (Central European Standard Time)] INFO Requests: 20999, requests per second: 300, mean latency: 24.2 ms
```

Considering each of the 8 workers will still be blocked for the time the SQLite query takes for each request, this seems to work pretty well to me.

It's still not going to serve thousands of requests per second with a single application (unless you are running on a Threadripper or something), but this should be more than good enough for the intended use cases.

I'll do some more tests (different numbers of workers/different loads) tomorrow and compare to the current solution before preparing for release.

**Comment by mserajnik** [comment]
I intend to. But I‘m not yet sure if i should add a hard limit (one worker per logical core) or not. That seems to be the sweet spot for most Node.js applications.

For now, I think I‘ll just have the default with one worker per logical core and the user can set that lower or higher as he wishes – with the caveat that using a number too high might be detrimental for performance (or even worse).
