### ISSUE TITLE
Danbooru-like API

### ISSUE THREAD

**Issue by DonaldTsang** [mserajnik/hydrusrv#11]
- [ ] Danbooru-compatible API https://danbooru.donmai.us/wiki_pages/43568
    - [ ] Moebooru variants https://konachan.com/help/api or https://yande.re/help/api
    - [ ] https://ghostbin.com/paste/hghv2 (a reduced form of Danbooru's API)
- [ ] Gelbooru-compatible API https://gelbooru.com/index.php?page=help&topic=dapi
- [ ] Sankaku-compatible API https://chan.sankakucomplex.com/help/api

**Comment by mserajnik** [comment]
Sorry, not interested/out of scope for this project.

**Comment by FredericaBernkastel** [comment]
@DonaldTsang But why scrape, if you have hydrus server running?

**Comment by mserajnik** [comment]
I think this isn't about scraping but rather rewriting the hydrusrv API (or adding additional variants of the API) to match the APIs other boorus use so apps that can consume those APIs would work with hydrusrv. See [here](https://github.com/rr-/szurubooru/issues/205) as well.

I don't want to go into extreme details why I wouldn't want this, but the main reason is that hydrusrv doesn't feature many of the things other softwares do (most of the time due to technical constraints, other times because it's out of scope or not important enough to invest the time needed, sometimes because I simply didn't find a satisfying solution that wouldn't degrade sync or query performance yet) and I therefore see no need to replicate those APIs, I'd rather roll my own easy-to-use variant like it is now.

hydrusrvue already works fine on mobile, imho better than many native apps. If you need to have the ability to access data from hydrusrv in a third party application, talk to the developers of those applications to add support or hard-fork hydrusrv and rewrite the API to work the way you want it too.

**Comment by DonaldTsang** [comment]
@mserajnik I am not saying that the API has to have everything that *booru has, but rather a subset of which makes porting would be easy and useful (e.g. search by query, viewing images) and not the others (e.g. "comments", "forums"), as most devs sees that nearly all *boorus follows the same REST-like pattern

**Comment by mserajnik** [comment]
@DonaldTsang 

> I am not saying that the API has to have everything that *booru has, but rather a subset

Alright, putting that point aside, it still boils down to three things, why I won't change the API (or add an additional one/let you optionally switch/whatever):

- In my opinion, this "standard API" is inferior to the one we currently use. I dislike stuff like `search[name] Allows searching for multiple exact tags seperated be commas` when you can just do `tags[]` like we do, which simplifies working with query builders like [qs](https://github.com/ljharb/qs) a lot
- I'm not interested in appealing to the developers of third party clients by adjusting the API of my project to confirm to a "standard" I'm personally not a fan of
- Too much work for something this project wouldn't gain anything from but instead make a part that works perfectly fine (the API) worse and/or more convoluted

Before I lock this conversation (this is wasting my time as well as yours since I won't budge), the last paragraph from my previous comment still stands:

> hydrusrvue already works fine on mobile, imho better than many native apps. If you need to have the ability to access data from hydrusrv in a third party application, talk to the developers of those applications to add support or hard-fork hydrusrv and rewrite the API to work the way you want it too.
