### ISSUE TITLE
Sorting tags

### ISSUE THREAD

**Issue by FredericaBernkastel** [mserajnik/hydrusrv#7]
**Autocomplete:**

1. Autocomplete results are always randomly shuffled. Do the same way as in hydrus: if tag matches exactly with the query, bring it to the top. The rest is ordered by file count.
![clipboard-82](https://user-images.githubusercontent.com/16236235/48567952-868ab100-e928-11e8-8f25-e46735dbc2da.png) ![clipboard-83](https://user-images.githubusercontent.com/16236235/48567954-868ab100-e928-11e8-876e-1fadd4518b60.png)

2. Do not hide autocomplete, if tag matches exactly with input!

3. Autocomplete for excluded tags does not work.

**Tags listing page:**
By default, tags are being sorted by id, say, randomly.
Sort them by descending file count.
If tag matches exacly with the search filter, again, bring it to the top.

**Single file page:**
Sort them by incidence, desc, grouped by namespace. (See in hydrus.)
Algorthm can be described such as:

First, you will split all tags into groups:
```
1. namespace a
2. namespace b
3. namespace c
...
4. unnamespaced
```
Namespace groups are sorted alphabetically.
Inside each group, tags are sorted by descending file count.

**Comment by mserajnik** [comment]
__Autocomplete:__ iirc, it‘s not sorted randomly, but alphabetically. But I do agree otherwise, should rather be sorted by file count (server-side), should get autocompletions for excluded tags (can be handled client-side, just need to leave out the minus when fetching autocomplete results) and exact matches shouldn‘t be excluded and pulled to the top instead (thats done client-side as well and needs to be adjusted there).

__Tags listing page:__ Sorting by file count is already possible and sorting by search input (and alphabetically in secondary sorting) as well. I like this behavior, so sorry, I don‘t want to have this changed.

__Single file page:__ Good idea, can easily be done client-side as well.

**Comment by FredericaBernkastel** [comment]
Also forgot, can you make the search case insensitive?

In the tags table, you will have 2 columns, first will contain lowercase version of tag (used in queries), second - original tag (will be displayed).

**Comment by mserajnik** [comment]
I‘m on mobile right now and can‘t look it up well, but isn‘t there some sort of natural sort (alphabetically, but numbers as numbers) in SQLite that would fix this?

If not, could probably be done via a custom function, right?

**Comment by mserajnik** [comment]
__Autocomplete:__ https://github.com/mserajnik/hydrusrv/commit/a7cca0db1be95abb60cfd4b737375175ad345eb4

Exact match is now always at the top, rest gets sorted by file count descending. The exact match is currently still excluded client-side, so that needs to be changed there (will do it together when working on #8).

__Namespace sorting:__ https://github.com/mserajnik/hydrusrv/commit/4a97954b0fefb9d04b8e69832d4d5b264dec1803

As suggested by you, I think that's good enough for our use cases. If you have three tags, `page:1`, `page:2` and `page:11`, before it the files would've been sorted by `1-11-2`, with these changes it will be by `1-2-11`.

Can you confirm these two changes working for you as described?

All the other tasks (except the tags listing changes that I said I won't do) are client-side.

Also, I've noticed that the tags on file detail pages are already sorted with namespaces first, and then alphabetically. So nothing to do here , imo. As I've said, I prefer the alphabetical sorting over the file count sorting on the detail page because it's far more likely that, while I'm on the detail page, I'm trying to check on a glance if a file has a specific tag (and that's easier to do when they are sorted alphabetically) than that I'm interested in how high the count is for each tag. The count is still visible anyway though, so it's not like that info is completely missing on the detail page.

**Comment by mserajnik** [comment]
Also: https://github.com/mserajnik/hydrusrv/commit/049c80b4fe36ffae8255b80195f7e0b5a31e2e5a

I think that's a neat addition, especially considering people might write other clients with different GUIs where a higher amount than 10 makes more sense than in hydrusrvue.

**Comment by FredericaBernkastel** [comment]
Works fine, good job!
